version: '3.1'
services:
  database:
    image: mysql:5.7
    restart: always
    volumes:
       - db_mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret

  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 9000:80
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: secret
      
volumes:
  db_mysql:
