version: '3.1'
services:
  mongodb:
    image: bitnami/mongodb:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/bitnami
    environment:
      - MONGODB_USERNAME=admin
      - MONGODB_PASSWORD=secret

volumes:
  mongodb_data:


