version: '3.1'
services:
  mysqldb:
    image: mysql:${MYSQL_VERSION}
    container_name: ${MYSQL_HOST}
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
       - db_mysql:/var/lib/mysql
    environment:
     - MYSQL_DATABASE=${MYSQL_DATABASE}
     - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

  phpmyadmin:
    depends_on:
      - mysqldb
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8888:80
    environment:
     - PMA_HOST=${MYSQL_HOST}
     - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
     - PHP_UPLOAD_MAX_FILESIZE=100MB

volumes:
  db_mysql:
